// @ts-nocheck
/**
 * Database Field Encryption Utility
 * Encrypts sensitive data at rest using AES-256-GCM
 *
 * Algorithm: AES-256-GCM (Galois/Counter Mode)
 * - Provides both confidentiality and authenticity
 * - Generates authentication tag to prevent tampering
 * - Uses random IV for each encryption
 * - Key: 256-bit derived from secret
 * - IV: 96-bit random (best practice for GCM)
 * - Auth Tag: 128-bit (16 bytes) generated by GCM mode
 *
 * Ciphertext Format: IV (12 bytes) + Ciphertext + Auth Tag (16 bytes)
 * This allows decryption without separate IV storage
 *
 * Sensitive Fields to Encrypt:
 * - agent.wallet_address
 * - agent.email_address (optional)
 * - payment.transaction_hash
 * - payment.payer_address
 * - External API keys
 *
 * Performance:
 * - AES-256-GCM hardware accelerated on modern CPUs
 * - ~1-2ms per encryption/decryption on standard hardware
 * - Suitable for database write-heavy workloads
 */

import crypto from "crypto";
import { logger } from "./logger.js";

/**
 * Encryption configuration
 */
interface EncryptionConfig {
  algorithm: string; // "aes-256-gcm"
  keyLength: number; // 32 bytes (256 bits)
  ivLength: number; // 12 bytes (96 bits) - standard for GCM
  authTagLength: number; // 16 bytes (128 bits)
}

/**
 * Configuration constants
 */
const CONFIG: EncryptionConfig = {
  algorithm: "aes-256-gcm",
  keyLength: 32,
  ivLength: 12,
  authTagLength: 16,
};

/**
 * Derive encryption key from secret using PBKDF2
 * (Salt is built into the key derivation)
 *
 * @param secret - Master secret (from environment variable)
 * @returns 256-bit encryption key
 */
function deriveKey(secret: string): Buffer {
  // Use PBKDF2 with SHA-256
  const iterations = 100000; // NIST recommends >=100k
  const salt = "clawzz-encryption-salt"; // Constant salt (key derivation, not for random IV)

  return crypto.pbkdf2Sync(
    secret,
    salt,
    iterations,
    CONFIG.keyLength,
    "sha256",
  );
}

/**
 * Encrypt a plaintext string using AES-256-GCM
 *
 * Process:
 * 1. Generate random IV (96-bit)
 * 2. Create cipher with IV
 * 3. Encrypt plaintext
 * 4. Generate authentication tag
 * 5. Combine IV + ciphertext + auth tag
 * 6. Encode as base64url for storage
 *
 * @param plaintext - Data to encrypt
 * @param encryptionSecret - Secret key (from environment)
 * @returns Base64url-encoded ciphertext
 * @throws Error if encryption fails
 */
export function encryptField(
  plaintext: string,
  encryptionSecret: string,
): string {
  try {
    if (!plaintext) {
      return plaintext; // Don't encrypt empty values
    }

    if (!encryptionSecret) {
      throw new Error("Encryption secret not provided");
    }

    // Derive key from secret
    const key = deriveKey(encryptionSecret);

    // Generate random IV
    const iv = crypto.randomBytes(CONFIG.ivLength);

    // Create cipher
    const cipher = crypto.createCipheriv(CONFIG.algorithm, key, iv);

    // Encrypt plaintext
    let encrypted = cipher.update(plaintext, "utf8", "hex");
    encrypted += cipher.final("hex");

    // Get authentication tag
    const authTag = cipher.getAuthTag();

    // Combine IV + ciphertext + auth tag and encode
    const combined = Buffer.concat([iv, Buffer.from(encrypted, "hex"), authTag]);
    const encoded = combined.toString("base64url");

    logger.debug("Field encrypted successfully", {
      plaintextLength: plaintext.length,
      encryptedLength: encoded.length,
      ivLength: CONFIG.ivLength,
      authTagLength: CONFIG.authTagLength,
    });

    return encoded;
  } catch (error) {
    logger.error("Field encryption failed", {
      error: error instanceof Error ? error.message : String(error),
    });
    throw error;
  }
}

/**
 * Decrypt a base64url-encoded ciphertext using AES-256-GCM
 *
 * Process:
 * 1. Decode base64url to buffer
 * 2. Extract IV (first 12 bytes)
 * 3. Extract auth tag (last 16 bytes)
 * 4. Extract ciphertext (middle bytes)
 * 5. Create decipher with IV
 * 6. Set authentication tag for verification
 * 7. Decrypt ciphertext
 * 8. Return plaintext
 *
 * @param ciphertext - Base64url-encoded encrypted data
 * @param encryptionSecret - Secret key (from environment)
 * @returns Decrypted plaintext
 * @throws Error if decryption fails or auth tag verification fails
 */
export function decryptField(
  ciphertext: string,
  encryptionSecret: string,
): string {
  try {
    if (!ciphertext) {
      return ciphertext; // Return empty values as-is
    }

    if (!encryptionSecret) {
      throw new Error("Encryption secret not provided");
    }

    // Decode base64url
    const combined = Buffer.from(ciphertext, "base64url");

    // Extract components
    const iv = combined.subarray(0, CONFIG.ivLength);
    const encrypted = combined.subarray(
      CONFIG.ivLength,
      combined.length - CONFIG.authTagLength,
    );
    const authTag = combined.subarray(combined.length - CONFIG.authTagLength);

    // Validate lengths
    if (iv.length !== CONFIG.ivLength) {
      throw new Error(
        `Invalid IV length: expected ${CONFIG.ivLength}, got ${iv.length}`,
      );
    }

    if (authTag.length !== CONFIG.authTagLength) {
      throw new Error(
        `Invalid auth tag length: expected ${CONFIG.authTagLength}, got ${authTag.length}`,
      );
    }

    // Derive key from secret
    const key = deriveKey(encryptionSecret);

    // Create decipher
    const decipher = crypto.createDecipheriv(CONFIG.algorithm, key, iv);

    // Set authentication tag for verification
    decipher.setAuthTag(authTag);

    // Decrypt
    let decrypted = decipher.update(encrypted.toString("hex"), "hex", "utf8");
    decrypted += decipher.final("utf8");

    logger.debug("Field decrypted successfully", {
      ciphertextLength: ciphertext.length,
      decryptedLength: decrypted.length,
    });

    return decrypted;
  } catch (error) {
    logger.error("Field decryption failed", {
      error: error instanceof Error ? error.message : String(error),
      ciphertextLength: ciphertext?.length || 0,
    });
    throw error;
  }
}

/**
 * Hash a plaintext value using PBKDF2
 * Use for sensitive fields that don't need to be decrypted (e.g., passwords)
 *
 * @param plaintext - Data to hash
 * @param encryptionSecret - Secret key for hash
 * @returns Base64 encoded hash
 */
export function hashField(plaintext: string, encryptionSecret: string): string {
  try {
    const hash = crypto.pbkdf2Sync(
      plaintext,
      encryptionSecret,
      100000,
      32,
      "sha256",
    );
    return hash.toString("base64");
  } catch (error) {
    logger.error("Field hashing failed", {
      error: error instanceof Error ? error.message : String(error),
    });
    throw error;
  }
}

/**
 * Verify a plaintext against a hash
 * Use with hashField() for sensitive comparisons
 *
 * @param plaintext - Value to verify
 * @param hash - Hash to compare against
 * @param encryptionSecret - Secret key used in hash
 * @returns true if plaintext matches hash, false otherwise
 */
export function verifyHashField(
  plaintext: string,
  hash: string,
  encryptionSecret: string,
): boolean {
  try {
    const computedHash = hashField(plaintext, encryptionSecret);
    // Use timing-safe comparison to prevent timing attacks
    return crypto.timingSafeEqual(
      Buffer.from(hash),
      Buffer.from(computedHash),
    );
  } catch (error) {
    logger.warn("Hash verification failed", {
      error: error instanceof Error ? error.message : String(error),
    });
    return false;
  }
}

/**
 * Test encryption/decryption round-trip
 * Used for validation and testing
 *
 * @param testSecret - Encryption secret to test
 * @returns true if encryption/decryption works, false otherwise
 */
export function validateEncryption(testSecret: string): boolean {
  try {
    const testData = "test-encryption-data-" + Date.now();
    const encrypted = encryptField(testData, testSecret);
    const decrypted = decryptField(encrypted, testSecret);

    if (decrypted !== testData) {
      logger.error("Encryption validation failed: data mismatch");
      return false;
    }

    logger.debug("Encryption validation passed");
    return true;
  } catch (error) {
    logger.error("Encryption validation failed", {
      error: error instanceof Error ? error.message : String(error),
    });
    return false;
  }
}

/**
 * Configuration information for logging
 */
export function getEncryptionInfo(): string {
  return (
    `AES-256-GCM | ` +
    `Key: ${CONFIG.keyLength * 8} bits | ` +
    `IV: ${CONFIG.ivLength * 8} bits | ` +
    `Auth Tag: ${CONFIG.authTagLength * 8} bits`
  );
}
